@echo off
REM ============================================================
REM  Clean Keil MDK-ARM build artifacts for GitHub upload
REM  Deletes intermediate/object/binary files generated by Keil,
REM  keeping only source code, project files and essential configs.
REM ============================================================

setlocal enabledelayedexpansion

REM --- Directories to remove (recursively) -----------------------
set "DIRS=build Build Objects Listings Debug Release .build"
REM Common Keil output folders:
REM   build/ Build/   - default MDK-ARM output folder
REM   Objects/        - legacy object folder
REM   Listings/       - .lst / .map listings
REM   Debug/ Release/ - configuration-specific output

REM --- File patterns to delete (in current dir and subdirs) -----
set "EXTS=*.o *.obj *.axf *.elf *.hex *.bin *.map *.lst *.crf *.d *.dep *.iex *.lnp *.htm *.build_log *.scvd *.ini"

echo.
echo ============================================================
echo  Keil Build Cleaner
echo  This will remove Keil-generated intermediate/build files.
echo ============================================================
echo.

set /p CONFIRM="Are you sure you want to clean? (Y/N): "
if /I not "%CONFIRM%"=="Y" (
    echo Aborted.
    goto :eof
)

echo.
echo [*] Removing build output directories...
for %%D in (%DIRS%) do (
    if exist "%%D" (
        echo     rmdir /s /q "%%D"
        rmdir /s /q "%%D" 2>nul
    )
)

echo.
echo [*] Removing Keil intermediate files...
for /R %%F in (%EXTS%) do (
    if exist "%%F" (
        echo     del "%%F"
        del /q "%%F" 2>nul
    )
)

echo.
echo [*] Removing Keil project user/misc files...
REM .uvoptx / .uvguix.*  are user-specific project options (regenerated by Keil)
for /R %%F in (*.uvoptx *.uvguix.*) do (
    if exist "%%F" (
        echo     del "%%F"
        del /q "%%F" 2>nul
    )
)

echo.
echo ============================================================
echo  Done. Keil build artifacts have been removed.
echo  Your source code and project (.uvprojx) are preserved.
echo ============================================================
echo.

endlocal
pause
